server:
  port: ${random.int[20040,20041]}

spring:
  redis:
    database: 7
    host: ${REDIS_HOST:redis.sunnly.wang}
    port: ${REDIS_PORT:6379}
    pool:
    max-active: 20

sunnly:
  redis:
    list:
      - name: oneTemplate
        database: 6
        host: ${REDIS_HOST:redis.sunnly.wang}
        port: ${REDIS_PORT:6379}
      - name: twoTemplate
        database: 8
        host: ${REDIS_HOST:redis.sunnly.wang}
        port: ${REDIS_PORT:6379}