server:
  port: ${random.int[20020,20021]}


spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.sunnly.wang:3306/sunnly-auth2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: sunnly
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1


sunnly:
  schedule:
#    refresh-client-token: "*/20 * * * * ?"
#    refresh-client-pubkey: "*/10 * * * * ?"
#    refresh-user-pubkey: "*/10 * * * * ?"
#    refresh-allowed-client: "*/5 * * * * ?"

    refresh-client-token: "* */30 * * * ?"
    refresh-client-pubkey: "* */40 * * * ?"
    refresh-user-pubkey: "* */50 * * * ?"
    refresh-allowed-client: "* */45 * * * ?"
  security:
    auth:
      service-id: sunnly-auth

      client:
#        signle-client: sunnly-auth  # 该方法配置后只允许此微服务访问，并且不去服务端验证
        id: sunnly-demo
        secret: sunnly
        token-header: x-client-token

      user:
        token-header: Authorization

#  禁用默认的http，启用okhttp
feign:
  sentinel:
    enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true
