server:
  port: ${random.int[7777,7778]}

storage:
  type: fastdfs
  fastdfs:
    tracker_server: 192.168.101.13:22122

fastdfs:
  base:
    url: http://192.168.101.13:8888/

spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: LEGACYHTML5